config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  match 'auth/:provider/callback/' => 'omniauth#shopify', via: :get
  root 'home#index'
  post 'home/fetch_data', as: 'fetch_data'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:shopify]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def fetch_data
    url = params[:url]
    seo_cheker = SeoChecker.new url
    resp, status = seo_cheker.perform
    render json: resp, status: status
  end
end

app/controllers/omniauth_controller.rb
class OmniauthController < ApplicationController

  def shopify
    puts request.env['omniauth.auth']
    redirect_to root_path
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/hello_world/index.html.erb
<h1 class="alert alert-info this-works">Client Rendering</h1>
<%= react_component("HelloWorldApp",
                     props: @hello_world_props,
                     prerender: false) %>

app/views/home/index.html.slim
= react_component("AppBar", props: { auth_url: "#{user_shopify_omniauth_authorize_path(shop: 'developer-test-5.myshopify.com')}" }, prerender: false)
.container
  .row
    .col-md-8.col-md-offset-2
      = react_component("UrlForm", props: { post_url: "#{fetch_data_path}"}, prerender: false)
  .row
    .col-md-12
      = react_component("DataTab", prerender: false)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trial</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>